version: '3.8'

services:
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6329"
    volumes:
      - redisdata:/var/lib/redis/data/

  db:
    restart: always
    image: postgres:12.4
    expose:
      - "5432"
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'my-secret-pw'
    volumes:
      - dbdata:/var/lib/postgresql/data/

#  11/1/2020 remove webgci
#  tcpeter:
#    restart: always
#    build: ./tcpeter
#    ports:
#      - "7224:7224"
#    environment:
#      PORT: 7224
#    depends_on:
#      - api-server
#    command: python -u serve.py

  api-relay:
    restart: always
    build: ./api-relay
    ports:
      - "7225:7225"
    environment:
      PORT: 7225
    depends_on:
      - api-server
    command: python -u serve.py

  api-server:
    restart: always
    build: ./api-server
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
      - redis
    volumes:
      - ./api-server/src:/server
    command: python manage.py runserver 0.0.0.0:8000


volumes:
  dbdata:
  redisdata:
