version: '3.8'

services:

  ui:
    command: "true" # Have this service do nothing
    restart: "no"

  nginx:
    build: ./ui
    ports:
      - "80:80"
      - "443:443"
    environment:
      - URL=home.breaker.rocks
      - VALIDATION=http
      - STAGING=true
    depends_on:
      - api-server
