version: '3.8'

services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6329"
    volumes:
      - redisdata:/var/lib/redis/data/

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'my-secret-pw'
    volumes:
      - dbdata:/var/lib/postgresql/data/

  tcpeter:
    restart: always
    build: ./tcpeter
    ports:
      - "7224:7224"
    environment:
      PORT: 7224
    depends_on:
      - api-server
    command: python -u serve.py

  api-relay:
    restart: always
    build: ./api-relay
    ports:
      - "7225:7225"
    environment:
      PORT: 7225
    depends_on:
      - api-server
    command: python -u serve.py

  api-server:
    restart: always
    build: ./api-server
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
      - redis
    volumes:
      - ./api-server/src:/server
    command: python manage.py runserver 0.0.0.0:8000

  ui:
    restart: always
    image: node
    ports:
      - "8080:8080"
    working_dir: /ui
    volumes:
      - ./ui/app:/ui
    command: npm run serve
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEV_PROXY=api-server
    stdin_open: true
    tty: true

volumes:
  dbdata:
  redisdata:
