version: '3.8'

services:
  nginx-dev:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-server
      - ui
