version: '3'

services:
  server:
    restart: always
    build: ./server
    expose:
      - "8000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    command: python manage.py runserver 0.0.0.0:8000

  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
       MYSQL_USER: 'root'
       MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    volumes:
      - mysqldata:/var/lib/postgresql/data/
volumes:
  mysqldata: