# vue build stage this code will create the static index.html and associated static files
FROM node as build-stage

WORKDIR /app
COPY ui/app/package*.json ./
RUN npm install
COPY ui/app .
RUN npm run build


# nginx server
FROM linuxserver/swag as production-stage

COPY nginx/nginx.conf /config/nginx/site-confs/default
COPY --from=build-stage /app/dist /config/www