# vue build stage this code will create the static index.html and associated static files
FROM node:lts-alpine as build-stage

WORKDIR /app
COPY ./app/package*.json ./
RUN npm install
COPY ./app .
RUN npm run build


# nginx server
FROM nginx as production-stage
COPY --from=build-stage /app/dist /config/www