name: CI

env:
  REGISTRY_URL: jtf191.azurecr.io

on:
  # this will launch every time there is a push to master
  push:
    branches: [ master ]

  # Launch from the github actions page
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build all microservices
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # build individual micro service components
    strategy:
      matrix:
        # listed here are the directories to build from
        component: [api-relay, api-server, tcpeter, gateway, ui]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Connect to Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build image
        run: docker image build ./${{matrix.component}} -t ${{env.REGISTRY_URL}}/${{matrix.component}}:latest

      - name: push image
        run: docker push ${{env.REGISTRY_URL}}/${{matrix.component}}:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: test
        run: echo hello world