# This is a basic workflow to help you get started with Actions

name: CI

env:
  REGISTRY_URL: jtf191.azurecr.io


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Connect to Azure Container Registry (ACR)
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: ./api-relay
#          push: true
#          tags: user/app:latest
#
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: test
        run: |
          docker image build ./api-relay -t ${{env.REGISTRY_URL}}/api-relay:test
          docker push ${{env.REGISTRY_URL}}/api-relay:test